# Generated by Django 5.1.5 on 2025-02-01 06:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurante',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='restaurante',
            name='bairro',
            field=models.CharField(default='', max_length=100, verbose_name='Bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurante',
            name='cep',
            field=models.CharField(default='', max_length=9, verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurante',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurante',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='inscricao_municipal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Inscrição Municipal'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='nome_restaurante',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do Restaurante'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='tipo_pessoa',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='endereco',
            field=models.CharField(default='', max_length=255, verbose_name='Endereço'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
