# Generated by Django 5.1.5 on 2025-02-02 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0002_remove_restaurante_criado_em_remove_restaurante_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestauranteFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='restaurante_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='restaurante.restaurante')),
            ],
        ),
    ]
