# Generated by Django 5.1.5 on 2025-02-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0003_restaurantefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='fator_correcao_financeiro',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Utilize esse fator para ajustes na precificação (ex: 1.00 = sem alteração, 1.10 = +10%)', max_digits=10, verbose_name='Fator Correção Financeiro'),
        ),
    ]
