# Generated by Django 5.1.5 on 2025-02-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0004_restaurante_fator_correcao_financeiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='fator_correcao_financeiro',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, help_text='Utilize esse fator para ajustes na precificação (ex: 1.00 = sem alteração, 1.10 = +10%)', max_digits=10, verbose_name='Fator Correção Financeiro'),
        ),
    ]
