# Generated by Django 5.1.5 on 2025-03-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0005_alter_restaurante_fator_correcao_financeiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='nome',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome'),
        ),
        migrations.DeleteModel(
            name='RestauranteFile',
        ),
    ]
