# Generated by Django 5.1.5 on 2025-03-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0006_restaurante_nome_delete_restaurantefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='restaurante/logos/', verbose_name='Logo'),
        ),
    ]
