# Generated by Django 5.1.6 on 2025-03-08 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumos', '0001_initial'),
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prato', models.CharField(default='RECEITA SEM NOME', max_length=255, verbose_name='NOME DO PRATO')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='receitas_imagens/', verbose_name='IMAGEM DO PRATO')),
                ('porcao_sugerida', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PORÇÃO SUGERIDA (EM G)')),
                ('tempo_preparo', models.IntegerField(verbose_name='TEMPO DE PREPARO (MIN)')),
                ('modo_preparo', models.TextField(blank=True, verbose_name='MODO DE PREPARO')),
                ('peso_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='PESO TOTAL DA PREPARAÇÃO (G)')),
                ('custo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='CUSTO TOTAL DA RECEITA (R$)')),
                ('preco_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='PREÇO DO KG (R$)')),
                ('valor_trabalhado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='VALOR TRABALHADO (R$)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='DATA DE CADASTRO')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='restaurante.restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='ReceitaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_utilizada', models.DecimalField(decimal_places=2, help_text='Informe a quantidade utilizada (na mesma unidade do insumo)', max_digits=10, verbose_name='QUANTIDADE UTILIZADA')),
                ('ajuste_tipo', models.CharField(blank=True, help_text="Tipo de ajuste: 'fc' para FATOR DE CORREÇÃO IC, 'ipc' para IPC ou vazio", max_length=10, null=True)),
                ('ajuste_sinal', models.CharField(blank=True, help_text="Sinal de ajuste: 'mais' ou 'menos'", max_length=10, null=True)),
                ('ajuste_percentual', models.DecimalField(blank=True, decimal_places=2, help_text='Valor percentual do ajuste', max_digits=5, null=True)),
                ('custo_utilizado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='CUSTO UTILIZADO (R$)')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos.insumo')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='receitas.receita')),
            ],
        ),
    ]
