# Generated by Django 5.1.5 on 2025-02-02 20:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0008_alter_insumo_restaurante'),
        ('receitas', '0001_initial'),
        ('restaurante', '0003_restaurantefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='nome',
        ),
        migrations.AddField(
            model_name='receita',
            name='custo_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo Total da Receita (R$)'),
        ),
        migrations.AddField(
            model_name='receita',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receita',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='receitas_imagens/', verbose_name='Imagem do Prato'),
        ),
        migrations.AddField(
            model_name='receita',
            name='nome_prato',
            field=models.CharField(default='Receita sem nome', max_length=255, verbose_name='Nome do Prato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receita',
            name='peso_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso Total da Preparação (g)'),
        ),
        migrations.AddField(
            model_name='receita',
            name='porcao_sugerida',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Porção Sugerida (em gramas)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receita',
            name='tempo_preparo',
            field=models.IntegerField(default=0, verbose_name='Tempo de Preparo (minutos)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receita',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='restaurante.restaurante'),
        ),
        migrations.CreateModel(
            name='ReceitaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_utilizada', models.DecimalField(decimal_places=2, help_text='Informe a quantidade utilizada na receita (na mesma unidade do insumo)', max_digits=10, verbose_name='Quantidade Utilizada')),
                ('custo_utilizado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo Utilizado (R$)')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos.insumo')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='receitas.receita')),
            ],
        ),
    ]
