# Generated by Django 5.1.5 on 2025-02-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_remove_receita_descricao_remove_receita_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='modo_preparo',
            field=models.TextField(blank=True, verbose_name='Modo de Preparo'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='nome_prato',
            field=models.CharField(default='Receita sem nome', max_length=255, verbose_name='Nome do Prato'),
        ),
        migrations.AlterField(
            model_name='receitainsumo',
            name='quantidade_utilizada',
            field=models.DecimalField(decimal_places=2, help_text='Informe a quantidade utilizada (na mesma unidade do insumo)', max_digits=10, verbose_name='Quantidade Utilizada'),
        ),
    ]
