# Generated by Django 5.1.5 on 2025-02-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_receita_preco_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receitainsumo',
            name='quantidade_utilizada',
            field=models.DecimalField(decimal_places=2, help_text='Informe a quantidade utilizada (na mesma unidade em que o insumo foi cadastrado)', max_digits=10, verbose_name='Quantidade Utilizada'),
        ),
    ]
