# Generated by Django 5.1.5 on 2025-02-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0005_alter_receitainsumo_quantidade_utilizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='receitainsumo',
            name='ajuste_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor percentual do ajuste', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='receitainsumo',
            name='ajuste_sinal',
            field=models.CharField(blank=True, help_text="Sinal de ajuste: 'mais' ou 'menos'", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='receitainsumo',
            name='ajuste_tipo',
            field=models.CharField(blank=True, help_text="Tipo de ajuste: 'fc' para FATOR DE CORREÇÃO IC, 'ipc' para IPC ou vazio para nenhum ajuste", max_length=10, null=True),
        ),
    ]
