# Generated by Django 5.1.5 on 2025-02-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0006_receitainsumo_ajuste_percentual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='valor_trabalhado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='VALOR TRABALHADO (R$)'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='custo_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='CUSTO TOTAL DA RECEITA (R$)'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='DATA DE CADASTRO'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='receitas_imagens/', verbose_name='IMAGEM DO PRATO'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='modo_preparo',
            field=models.TextField(blank=True, verbose_name='MODO DE PREPARO'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='nome_prato',
            field=models.CharField(default='RECEITA SEM NOME', max_length=255, verbose_name='NOME DO PRATO'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='peso_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='PESO TOTAL DA PREPARAÇÃO (G)'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='porcao_sugerida',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PORÇÃO SUGERIDA (EM G)'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='preco_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='PREÇO DO KG (R$)'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='tempo_preparo',
            field=models.IntegerField(verbose_name='TEMPO DE PREPARO (MIN)'),
        ),
        migrations.AlterField(
            model_name='receitainsumo',
            name='ajuste_tipo',
            field=models.CharField(blank=True, help_text="Tipo de ajuste: 'fc' para FATOR DE CORREÇÃO IC, 'ipc' para IPC ou vazio", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='receitainsumo',
            name='custo_utilizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='CUSTO UTILIZADO (R$)'),
        ),
        migrations.AlterField(
            model_name='receitainsumo',
            name='quantidade_utilizada',
            field=models.DecimalField(decimal_places=2, help_text='Informe a quantidade utilizada (na mesma unidade do insumo)', max_digits=10, verbose_name='QUANTIDADE UTILIZADA'),
        ),
    ]
