# Generated by Django 5.1.6 on 2025-03-08 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('unidade_medida', models.CharField(choices=[('unidade', 'Unidade'), ('caixa', 'Caixa'), ('kg', 'Quilograma'), ('g', 'Grama'), ('ml', 'Mililitro'), ('l', 'Litro')], max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('restaurante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='restaurante.restaurante', verbose_name='Restaurante')),
            ],
            options={
                'unique_together': {('restaurante', 'nome')},
            },
        ),
    ]
