# Generated by Django 5.1.5 on 2025-02-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insumo',
            old_name='valor',
            new_name='preco',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='restaurante',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='unidade_de_medida',
        ),
        migrations.AddField(
            model_name='insumo',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='unidade_medida',
            field=models.CharField(choices=[('unidade', 'Unidade'), ('caixa', 'Caixa'), ('kg', 'Quilograma'), ('g', 'Grama'), ('ml', 'Mililitro'), ('l', 'Litro')], default='unidade', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='insumo',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
