# Generated by Django 5.1.5 on 2025-02-01 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0003_insumo_restaurante'),
        ('restaurante', '0002_remove_restaurante_criado_em_remove_restaurante_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='restaurante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='restaurante.restaurante', verbose_name='Restaurante'),
        ),
    ]
