# Generated by Django 5.1.5 on 2025-02-01 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0005_alter_insumo_restaurante'),
        ('insumos', '0006_auto_20250201_1934'),
    ]

    operations = [
    ]
