# Generated by Django 5.1.5 on 2025-02-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0008_alter_insumo_restaurante'),
        ('restaurante', '0005_alter_restaurante_fator_correcao_financeiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='insumo',
            unique_together={('restaurante', 'nome')},
        ),
    ]
