# Generated by Django 5.1.5 on 2025-02-02 23:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas_tecnicas', '0001_initial'),
        ('insumos', '0008_alter_insumo_restaurante'),
        ('restaurante', '0004_restaurante_fator_correcao_financeiro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichatecnica',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='fichatecnica',
            name='nome',
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='custo_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo Total da Ficha Técnica (R$)'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='fichas_tecnicas_imagens/', verbose_name='Imagem do Prato'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='modo_preparo',
            field=models.TextField(blank=True, verbose_name='Modo de Preparo'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='nome_prato',
            field=models.CharField(default='Ficha Técnica sem nome', max_length=255, verbose_name='Nome do Prato'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='peso_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso Total da Preparação (g)'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='porcao_sugerida',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Porção Sugerida (em gramas)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='tempo_preparo',
            field=models.IntegerField(default=0, verbose_name='Tempo de Preparo (minutos)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_tecnicas', to='restaurante.restaurante'),
        ),
        migrations.CreateModel(
            name='FichaTecnicaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_utilizada', models.DecimalField(decimal_places=2, help_text='Informe a quantidade utilizada (na mesma unidade do insumo)', max_digits=10, verbose_name='Quantidade Utilizada')),
                ('custo_utilizado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo Utilizado (R$)')),
                ('ficha_tecnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='fichas_tecnicas.fichatecnica')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumos.insumo')),
            ],
        ),
        migrations.DeleteModel(
            name='ReceitaFichaTecnica',
        ),
    ]
