# Generated by Django 5.1.5 on 2025-02-03 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas_tecnicas', '0002_remove_fichatecnica_descricao_and_more'),
        ('receitas', '0004_receita_preco_kg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichatecnica',
            name='custo_total',
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='custo_total_insumos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo Total dos Insumos (R$)'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='custo_total_receitas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo Total das Receitas (R$)'),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='valor_venda_sugerida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor de Venda Sugerida (R$)'),
        ),
        migrations.AlterField(
            model_name='fichatecnicainsumo',
            name='ficha_tecnica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_insumos', to='fichas_tecnicas.fichatecnica'),
        ),
        migrations.CreateModel(
            name='FichaTecnicaReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_utilizada', models.DecimalField(decimal_places=2, help_text='Informe a quantidade utilizada da receita na ficha (na unidade escolhida)', max_digits=10, verbose_name='Quantidade Utilizada')),
                ('unidade', models.CharField(default='g', max_length=10, verbose_name='Unidade')),
                ('custo_utilizado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo Utilizado (R$)')),
                ('ficha_tecnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_receitas', to='fichas_tecnicas.fichatecnica')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.receita')),
            ],
        ),
    ]
