# Generated by Django 5.1.5 on 2025-02-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas_tecnicas', '0003_remove_fichatecnica_custo_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichatecnicainsumo',
            name='ajuste_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Para 'fator': percentual de acréscimo ou desconto. Para 'ipc': porcentagem da parte comestível (ex.: 70 para 70%)", max_digits=5, null=True, verbose_name='Percentual de Ajuste (%)'),
        ),
        migrations.AddField(
            model_name='fichatecnicainsumo',
            name='ajuste_sinal',
            field=models.CharField(blank=True, help_text="Informe 'mais' ou 'menos' (apenas para Fator de Correção); para IPC, este campo pode ser ignorado", max_length=10, null=True, verbose_name='Sinal do Ajuste'),
        ),
        migrations.AddField(
            model_name='fichatecnicainsumo',
            name='ajuste_tipo',
            field=models.CharField(blank=True, help_text="Informe 'fator' para Fator de Correção e Cocção ou 'ipc' para Indicador de Parte Comestível", max_length=10, null=True, verbose_name='Tipo de Ajuste'),
        ),
    ]
