# Generated by Django 5.1.5 on 2025-02-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas_tecnicas', '0004_fichatecnicainsumo_ajuste_percentual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichatecnica',
            name='valor_trabalhado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='VALOR TRABALHADO (R$)'),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='custo_total_insumos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='CUSTO TOTAL DOS INSUMOS (R$)'),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='custo_total_receitas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='CUSTO TOTAL DAS RECEITAS (R$)'),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='DATA DE CADASTRO'),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='fichas_tecnicas_imagens/', verbose_name='IMAGEM DO PRATO'),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='modo_preparo',
            field=models.TextField(blank=True, verbose_name='MODO DE PREPARO'),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='nome_prato',
            field=models.CharField(default='FICHA TÉCNICA SEM NOME', max_length=255, verbose_name='NOME DO PRATO'),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='peso_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='PESO TOTAL DA PREPARAÇÃO (G)'),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='porcao_sugerida',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='PORÇÃO SUGERIDA (EM GRAMAS)'),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='tempo_preparo',
            field=models.IntegerField(verbose_name='TEMPO DE PREPARO (MIN)'),
        ),
        migrations.AlterField(
            model_name='fichatecnica',
            name='valor_venda_sugerida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='VALOR DE VENDA SUGERIDA (R$)'),
        ),
        migrations.AlterField(
            model_name='fichatecnicainsumo',
            name='ajuste_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ex.: 70 para 70%', max_digits=5, null=True, verbose_name='PERCENTUAL DE AJUSTE (%)'),
        ),
        migrations.AlterField(
            model_name='fichatecnicainsumo',
            name='ajuste_sinal',
            field=models.CharField(blank=True, help_text="Informe 'mais' ou 'menos'", max_length=10, null=True, verbose_name='SINAL DO AJUSTE'),
        ),
        migrations.AlterField(
            model_name='fichatecnicainsumo',
            name='ajuste_tipo',
            field=models.CharField(blank=True, help_text="Informe 'fator' para FATOR DE CORREÇÃO IC ou 'ipc' para IPC", max_length=10, null=True, verbose_name='TIPO DE AJUSTE'),
        ),
        migrations.AlterField(
            model_name='fichatecnicainsumo',
            name='custo_utilizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='CUSTO UTILIZADO (R$)'),
        ),
        migrations.AlterField(
            model_name='fichatecnicainsumo',
            name='quantidade_utilizada',
            field=models.DecimalField(decimal_places=2, help_text='Informe a quantidade utilizada (na mesma unidade do insumo)', max_digits=10, verbose_name='QUANTIDADE UTILIZADA'),
        ),
        migrations.AlterField(
            model_name='fichatecnicareceita',
            name='custo_utilizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='CUSTO UTILIZADO (R$)'),
        ),
        migrations.AlterField(
            model_name='fichatecnicareceita',
            name='quantidade_utilizada',
            field=models.DecimalField(decimal_places=2, help_text='Informe a quantidade utilizada da receita na ficha (na unidade escolhida)', max_digits=10, verbose_name='QUANTIDADE UTILIZADA'),
        ),
        migrations.AlterField(
            model_name='fichatecnicareceita',
            name='unidade',
            field=models.CharField(default='g', max_length=10, verbose_name='UNIDADE'),
        ),
    ]
